// settings-style.js — 設定面板樣式注入
// 來源：mockups/settings-redesign.html 的 <style>，取 .m2kai-root 以下全部規則
//（含 @supports OKLCH fallback、深色 token、prefers-reduced-motion、@keyframes、reset）。
// 已剔除 mockup 的「預覽舞台」規則（body{} / .m2kai-stage / 針對 body 的 prefers-dark），
// 並新增 .m2kai-overlay modal 遮罩（讓面板置中，點遮罩關閉由 JS 處理）。
//
// 風格鐵則：CSS 以陣列 join 串接、外層 JS 用單引號；CSS 內部字串（font-family 引號、
// content）用雙引號，與外層單引號不衝突。全檔無反引號 template literal。
// 匯出：ensureSettingsStyle（裸宣告 function）。topDoc 沿用 utils.js 既有定義。

function ensureSettingsStyle() {
  var d = topDoc();
  if (d.getElementById('m2kaiStyle')) return;

  var css = [
    '/* ---- Modal 遮罩：讓面板置中浮在宿主頁面之上（點遮罩關閉由 JS 處理） ---- */',
    '.m2kai-overlay {',
    '  position: fixed;',
    '  inset: 0;',
    '  z-index: 2147483646;',
    '  display: flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  background: rgba(0, 0, 0, .45);',
    '}',
    '',
    '/* =========================================================================',
    '   Design tokens — 全部 OKLCH（關鍵色補 rgb fallback，見下方 @supports 段）',
    '   淺色預設；深色由共享規則覆寫同一組變數。',
    '   spacing scale（嚴格 4 模數，全檔只用這六階）。',
    '   ========================================================================= */',
    '.m2kai-root {',
    '  --m2kai-accent: oklch(0.55 0.19 264);',
    '  --m2kai-accent-strong: oklch(0.49 0.20 264);',
    '  --m2kai-accent-weak: oklch(0.55 0.19 264 / 0.12);',
    '  --m2kai-accent-ring: oklch(0.55 0.19 264 / 0.40);',
    '  --m2kai-on-accent: oklch(0.99 0 0);',
    '',
    '  --m2kai-brand: var(--m2kai-accent);',
    '  --m2kai-brand-weak: oklch(0.55 0.19 264 / 0.12);',
    '',
    '  --m2kai-bg: oklch(0.99 0.002 264);',
    '  --m2kai-surface: oklch(1 0 0);',
    '  --m2kai-surface-2: oklch(0.965 0.004 264);',
    '  --m2kai-surface-3: oklch(0.93 0.006 264);',
    '  --m2kai-fg: oklch(0.22 0.01 264);',
    '  --m2kai-fg-muted: oklch(0.50 0.01 264);',
    '  --m2kai-fg-faint: oklch(0.64 0.01 264);',
    '  --m2kai-border: oklch(0.90 0.005 264);',
    '  --m2kai-border-strong: oklch(0.83 0.006 264);',
    '  --m2kai-field-bg: oklch(0.995 0.002 264);',
    '',
    '  --m2kai-success: oklch(0.58 0.14 152);',
    '  --m2kai-success-weak: oklch(0.58 0.14 152 / 0.14);',
    '  --m2kai-success-border: oklch(0.58 0.14 152 / 0.45);',
    '  --m2kai-warn: oklch(0.60 0.14 75);',
    '  --m2kai-warn-weak: oklch(0.74 0.15 85 / 0.16);',
    '  --m2kai-danger: oklch(0.58 0.21 27);',
    '  --m2kai-danger-weak: oklch(0.58 0.21 27 / 0.12);',
    '  --m2kai-danger-border: oklch(0.58 0.21 27 / 0.45);',
    '  --m2kai-link: oklch(0.55 0.16 250);',
    '',
    '  --m2kai-s1: 4px;',
    '  --m2kai-s2: 8px;',
    '  --m2kai-s3: 12px;',
    '  --m2kai-s4: 16px;',
    '  --m2kai-s5: 24px;',
    '  --m2kai-s6: 32px;',
    '',
    '  --m2kai-radius-lg: 10px;',
    '  --m2kai-radius-md: 8px;',
    '  --m2kai-radius-sm: 6px;',
    '  --m2kai-shadow: 0 8px 40px oklch(0 0 0 / 0.08);',
    '  --m2kai-shadow-pop: 0 12px 48px oklch(0 0 0 / 0.18);',
    '',
    '  --m2kai-mono: ui-monospace, SFMono-Regular, "SF Mono", Menlo, Consolas, "Liberation Mono", monospace;',
    '  --m2kai-sans: "Microsoft JhengHei", "PingFang TC", ui-sans-serif, system-ui, sans-serif;',
    '}',
    '',
    '/* ---- 深色變數：prefers 與手動 data-theme 共用 ---- */',
    '@media (prefers-color-scheme: dark) {',
    '  .m2kai-root:not([data-m2kai-theme="light"]) { color-scheme: dark; }',
    '}',
    '.m2kai-root[data-m2kai-theme="dark"],',
    '.m2kai-dark-vars {',
    '  color-scheme: dark;',
    '}',
    '@media (prefers-color-scheme: dark) {',
    '  .m2kai-root:not([data-m2kai-theme="light"]) {',
    '    --m2kai-accent: oklch(0.68 0.16 264);',
    '    --m2kai-accent-strong: oklch(0.74 0.15 264);',
    '    --m2kai-accent-weak: oklch(0.68 0.16 264 / 0.18);',
    '    --m2kai-accent-ring: oklch(0.68 0.16 264 / 0.45);',
    '    --m2kai-on-accent: oklch(0.16 0.01 264);',
    '    --m2kai-brand: var(--m2kai-accent);',
    '    --m2kai-brand-weak: oklch(0.68 0.16 264 / 0.18);',
    '    --m2kai-bg: oklch(0.16 0.006 264);',
    '    --m2kai-surface: oklch(0.205 0.007 264);',
    '    --m2kai-surface-2: oklch(0.245 0.008 264);',
    '    --m2kai-surface-3: oklch(0.30 0.010 264);',
    '    --m2kai-fg: oklch(0.94 0.004 264);',
    '    --m2kai-fg-muted: oklch(0.72 0.008 264);',
    '    --m2kai-fg-faint: oklch(0.58 0.01 264);',
    '    --m2kai-border: oklch(1 0 0 / 0.10);',
    '    --m2kai-border-strong: oklch(1 0 0 / 0.16);',
    '    --m2kai-field-bg: oklch(0.185 0.007 264);',
    '    --m2kai-success: oklch(0.70 0.14 152);',
    '    --m2kai-success-weak: oklch(0.70 0.14 152 / 0.16);',
    '    --m2kai-success-border: oklch(0.70 0.14 152 / 0.40);',
    '    --m2kai-warn: oklch(0.80 0.14 85);',
    '    --m2kai-warn-weak: oklch(0.80 0.14 85 / 0.16);',
    '    --m2kai-danger: oklch(0.68 0.18 27);',
    '    --m2kai-danger-weak: oklch(0.68 0.18 27 / 0.16);',
    '    --m2kai-danger-border: oklch(0.68 0.18 27 / 0.40);',
    '    --m2kai-link: oklch(0.72 0.13 250);',
    '    --m2kai-shadow: 0 8px 40px oklch(0 0 0 / 0.45);',
    '    --m2kai-shadow-pop: 0 16px 60px oklch(0 0 0 / 0.6);',
    '  }',
    '}',
    '.m2kai-root[data-m2kai-theme="dark"] {',
    '  --m2kai-accent: oklch(0.68 0.16 264);',
    '  --m2kai-accent-strong: oklch(0.74 0.15 264);',
    '  --m2kai-accent-weak: oklch(0.68 0.16 264 / 0.18);',
    '  --m2kai-accent-ring: oklch(0.68 0.16 264 / 0.45);',
    '  --m2kai-on-accent: oklch(0.16 0.01 264);',
    '  --m2kai-brand: var(--m2kai-accent);',
    '  --m2kai-brand-weak: oklch(0.68 0.16 264 / 0.18);',
    '  --m2kai-bg: oklch(0.16 0.006 264);',
    '  --m2kai-surface: oklch(0.205 0.007 264);',
    '  --m2kai-surface-2: oklch(0.245 0.008 264);',
    '  --m2kai-surface-3: oklch(0.30 0.010 264);',
    '  --m2kai-fg: oklch(0.94 0.004 264);',
    '  --m2kai-fg-muted: oklch(0.72 0.008 264);',
    '  --m2kai-fg-faint: oklch(0.58 0.01 264);',
    '  --m2kai-border: oklch(1 0 0 / 0.10);',
    '  --m2kai-border-strong: oklch(1 0 0 / 0.16);',
    '  --m2kai-field-bg: oklch(0.185 0.007 264);',
    '  --m2kai-success: oklch(0.70 0.14 152);',
    '  --m2kai-success-weak: oklch(0.70 0.14 152 / 0.16);',
    '  --m2kai-success-border: oklch(0.70 0.14 152 / 0.40);',
    '  --m2kai-warn: oklch(0.80 0.14 85);',
    '  --m2kai-warn-weak: oklch(0.80 0.14 85 / 0.16);',
    '  --m2kai-danger: oklch(0.68 0.18 27);',
    '  --m2kai-danger-weak: oklch(0.68 0.18 27 / 0.16);',
    '  --m2kai-danger-border: oklch(0.68 0.18 27 / 0.40);',
    '  --m2kai-link: oklch(0.72 0.13 250);',
    '  --m2kai-shadow: 0 8px 40px oklch(0 0 0 / 0.45);',
    '  --m2kai-shadow-pop: 0 16px 60px oklch(0 0 0 / 0.6);',
    '}',
    '',
    '/* =========================================================================',
    '   OKLCH fallback — 舊瀏覽器解析失敗時退到 sRGB 近似值。',
    '   ========================================================================= */',
    '@supports not (color: oklch(0.5 0.1 264)) {',
    '  .m2kai-root {',
    '    --m2kai-accent: #4f46e5;',
    '    --m2kai-accent-strong: #4338ca;',
    '    --m2kai-accent-weak: rgba(79, 70, 229, 0.12);',
    '    --m2kai-accent-ring: rgba(79, 70, 229, 0.40);',
    '    --m2kai-on-accent: #ffffff;',
    '    --m2kai-brand: #4f46e5;',
    '    --m2kai-brand-weak: rgba(79, 70, 229, 0.12);',
    '    --m2kai-bg: #fbfbfc;',
    '    --m2kai-surface: #ffffff;',
    '    --m2kai-surface-2: #f1f2f5;',
    '    --m2kai-surface-3: #e3e5ea;',
    '    --m2kai-fg: #23262e;',
    '    --m2kai-fg-muted: #6b7080;',
    '    --m2kai-fg-faint: #9aa0ad;',
    '    --m2kai-border: #e2e4ea;',
    '    --m2kai-border-strong: #cbcfd8;',
    '    --m2kai-field-bg: #fdfdfe;',
    '    --m2kai-success: #1f9d5b;',
    '    --m2kai-success-weak: rgba(31, 157, 91, 0.14);',
    '    --m2kai-success-border: rgba(31, 157, 91, 0.45);',
    '    --m2kai-warn: #9a6b00;',
    '    --m2kai-warn-weak: rgba(214, 158, 46, 0.16);',
    '    --m2kai-danger: #d33636;',
    '    --m2kai-danger-weak: rgba(211, 54, 54, 0.12);',
    '    --m2kai-danger-border: rgba(211, 54, 54, 0.45);',
    '    --m2kai-link: #3b6fe0;',
    '  }',
    '}',
    '',
    '/* =========================================================================',
    '   Scope reset — 把面板內元素從宿主頁面的樣式中隔離。',
    '   ========================================================================= */',
    '.m2kai-root, .m2kai-root * {',
    '  box-sizing: border-box;',
    '}',
    '.m2kai-root {',
    '  font-family: var(--m2kai-sans);',
    '  font-size: 14px;',
    '  line-height: 1.45;',
    '  color: var(--m2kai-fg);',
    '  -webkit-font-smoothing: antialiased;',
    '}',
    '.m2kai-root button,',
    '.m2kai-root input,',
    '.m2kai-root select,',
    '.m2kai-root textarea {',
    '  font-family: inherit;',
    '  font-size: inherit;',
    '  line-height: normal;',
    '  color: inherit;',
    '  margin: 0;',
    '  letter-spacing: inherit;',
    '  text-transform: none;',
    '}',
    '',
    '/* =========================================================================',
    '   面板外殼',
    '   ========================================================================= */',
    '.m2kai-panel {',
    '  width: 840px;',
    '  max-width: 96vw;',
    '  height: 600px;',
    '  max-height: 92vh;',
    '  background: var(--m2kai-surface);',
    '  border: 1px solid var(--m2kai-border);',
    '  border-radius: var(--m2kai-radius-lg);',
    '  box-shadow: var(--m2kai-shadow);',
    '  display: flex;',
    '  flex-direction: column;',
    '  overflow: hidden;',
    '  animation: m2kai-pop 0.16s cubic-bezier(0.2, 0.8, 0.3, 1);',
    '}',
    '@keyframes m2kai-pop {',
    '  from { opacity: 0; transform: translateY(6px) scale(0.985); }',
    '  to   { opacity: 1; transform: translateY(0) scale(1); }',
    '}',
    '',
    '/* ---- Header ---- */',
    '.m2kai-header {',
    '  position: relative;',
    '  display: flex;',
    '  align-items: center;',
    '  gap: var(--m2kai-s3);',
    '  padding: var(--m2kai-s4) var(--m2kai-s4);',
    '  border-bottom: 1px solid var(--m2kai-border);',
    '  background:',
    '    linear-gradient(180deg, var(--m2kai-brand-weak), transparent 90%),',
    '    var(--m2kai-surface);',
    '  transition: background 0.4s ease;',
    '}',
    '.m2kai-logo {',
    '  position: relative;',
    '  width: 34px; height: 34px;',
    '  flex: none;',
    '  display: grid;',
    '  place-items: center;',
    '  border-radius: var(--m2kai-radius-md);',
    '  background: var(--m2kai-brand-weak);',
    '  color: var(--m2kai-brand);',
    '  transition: background 0.4s ease, color 0.4s ease;',
    '}',
    '.m2kai-logo::after {',
    '  content: "";',
    '  position: absolute;',
    '  inset: -4px;',
    '  border-radius: inherit;',
    '  background: var(--m2kai-brand);',
    '  opacity: 0;',
    '  z-index: -1;',
    '  animation: m2kai-breathe 3.2s ease-in-out infinite;',
    '}',
    '@keyframes m2kai-breathe {',
    '  0%, 100% { opacity: 0.06; transform: scale(1); }',
    '  50%      { opacity: 0.18; transform: scale(1.06); }',
    '}',
    '.m2kai-title-wrap { display: flex; flex-direction: column; gap: 1px; }',
    '.m2kai-title-row { display: flex; align-items: center; gap: var(--m2kai-s2); }',
    '.m2kai-title {',
    '  margin: 0;',
    '  font-size: 16px;',
    '  font-weight: 700;',
    '  letter-spacing: -0.01em;',
    '}',
    '.m2kai-subtitle {',
    '  font-size: 12px;',
    '  color: var(--m2kai-fg-muted);',
    '}',
    '.m2kai-header-spacer { flex: 1; }',
    '.m2kai-iconbtn {',
    '  width: 30px; height: 30px;',
    '  display: grid; place-items: center;',
    '  border: 1px solid var(--m2kai-border);',
    '  background: var(--m2kai-surface);',
    '  border-radius: var(--m2kai-radius-md);',
    '  color: var(--m2kai-fg-muted);',
    '  cursor: pointer;',
    '  transition: background 0.13s, color 0.13s, border-color 0.13s;',
    '}',
    '.m2kai-iconbtn:hover { background: var(--m2kai-surface-2); color: var(--m2kai-fg); }',
    '.m2kai-iconbtn:focus-visible { outline: none; box-shadow: 0 0 0 3px var(--m2kai-accent-ring); }',
    '.m2kai-close { font-size: 20px; line-height: 1; }',
    '',
    '.m2kai-safety-badge {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  gap: var(--m2kai-s1);',
    '  height: 19px;',
    '  padding: 0 var(--m2kai-s2);',
    '  border-radius: 999px;',
    '  font-size: 11px;',
    '  font-weight: 600;',
    '  background: var(--m2kai-success-weak);',
    '  color: var(--m2kai-success);',
    '  border: 1px solid var(--m2kai-success-border);',
    '  white-space: nowrap;',
    '}',
    '.m2kai-safety-badge .m2kai-ico { width: 12px; height: 12px; }',
    '',
    '/* ---- Tabs ---- */',
    '.m2kai-tabs {',
    '  display: flex;',
    '  gap: 2px;',
    '  padding: var(--m2kai-s2) var(--m2kai-s3) 0;',
    '  border-bottom: 1px solid var(--m2kai-border);',
    '  background: var(--m2kai-surface);',
    '}',
    '.m2kai-tab {',
    '  position: relative;',
    '  appearance: none;',
    '  border: none;',
    '  background: transparent;',
    '  padding: var(--m2kai-s2) var(--m2kai-s3) 10px;',
    '  font-size: 13px;',
    '  font-weight: 500;',
    '  color: var(--m2kai-fg-muted);',
    '  cursor: pointer;',
    '  border-radius: var(--m2kai-radius-sm) var(--m2kai-radius-sm) 0 0;',
    '  transition: color 0.13s, background 0.13s;',
    '  display: flex;',
    '  align-items: center;',
    '  gap: var(--m2kai-s1);',
    '}',
    '.m2kai-tab:hover { color: var(--m2kai-fg); background: var(--m2kai-surface-2); }',
    '.m2kai-tab:focus-visible { outline: none; box-shadow: 0 0 0 3px var(--m2kai-accent-ring); }',
    '.m2kai-tab[aria-selected="true"] { color: var(--m2kai-accent-strong); font-weight: 700; }',
    '.m2kai-tab .m2kai-ico { width: 15px; height: 15px; }',
    '.m2kai-tab::after {',
    '  content: "";',
    '  position: absolute;',
    '  left: 10px; right: 10px; bottom: -1px;',
    '  height: 2px;',
    '  border-radius: 2px;',
    '  background: var(--m2kai-accent);',
    '  transform: scaleX(0);',
    '  transform-origin: center;',
    '  transition: transform 0.16s cubic-bezier(0.2, 0.8, 0.3, 1);',
    '}',
    '.m2kai-tab[aria-selected="true"]::after { transform: scaleX(1); }',
    '',
    '/* ---- Body ---- */',
    '.m2kai-body {',
    '  flex: 1;',
    '  overflow: hidden;',
    '  position: relative;',
    '}',
    '.m2kai-page {',
    '  position: absolute;',
    '  inset: 0;',
    '  overflow: auto;',
    '  opacity: 0;',
    '  visibility: hidden;',
    '  transform: translateY(4px);',
    '  transition: opacity 0.15s ease, transform 0.15s ease, visibility 0s linear 0.15s;',
    '  pointer-events: none;',
    '}',
    '.m2kai-page.is-active {',
    '  opacity: 1;',
    '  visibility: visible;',
    '  transform: none;',
    '  pointer-events: auto;',
    '  transition: opacity 0.15s ease, transform 0.15s ease, visibility 0s linear 0s;',
    '}',
    '',
    '/* =========================================================================',
    '   Tab 1 供應商 — master-detail',
    '   ========================================================================= */',
    '.m2kai-md {',
    '  display: grid;',
    '  grid-template-columns: 248px 1fr;',
    '  height: 100%;',
    '}',
    '.m2kai-md-list {',
    '  border-right: 1px solid var(--m2kai-border);',
    '  background: var(--m2kai-surface-2);',
    '  overflow: auto;',
    '  padding: var(--m2kai-s3);',
    '  display: flex;',
    '  flex-direction: column;',
    '  gap: var(--m2kai-s2);',
    '}',
    '.m2kai-list-label {',
    '  font-size: 11px;',
    '  font-weight: 700;',
    '  letter-spacing: 0.06em;',
    '  text-transform: uppercase;',
    '  color: var(--m2kai-fg-faint);',
    '  padding: 2px var(--m2kai-s1);',
    '}',
    '',
    '.m2kai-pcard {',
    '  position: relative;',
    '  display: flex;',
    '  align-items: center;',
    '  gap: var(--m2kai-s2);',
    '  padding: var(--m2kai-s2) var(--m2kai-s3);',
    '  border: 1px solid var(--m2kai-border);',
    '  background: var(--m2kai-surface);',
    '  border-radius: var(--m2kai-radius-md);',
    '  cursor: pointer;',
    '  text-align: left;',
    '  width: 100%;',
    '  transition: border-color 0.13s, box-shadow 0.13s, transform 0.13s, background 0.13s;',
    '}',
    '.m2kai-pcard:hover { border-color: var(--m2kai-border-strong); transform: translateY(-1px); }',
    '.m2kai-pcard:focus-visible { outline: none; box-shadow: 0 0 0 3px var(--m2kai-accent-ring); }',
    '',
    '.m2kai-pcard.is-selected {',
    '  background: var(--m2kai-surface-3);',
    '  border-color: var(--m2kai-border-strong);',
    '}',
    '',
    '.m2kai-pcard.is-active {',
    '  border-color: var(--m2kai-brand);',
    '  box-shadow: 0 0 0 1px var(--m2kai-brand), 0 4px 16px var(--m2kai-brand-weak);',
    '}',
    '.m2kai-pcard.is-active::before {',
    '  content: "";',
    '  position: absolute;',
    '  left: 0; top: 6px; bottom: 6px;',
    '  width: 3px;',
    '  border-radius: 0 3px 3px 0;',
    '  background: var(--m2kai-brand);',
    '}',
    '.m2kai-avatar {',
    '  width: 30px; height: 30px;',
    '  flex: none;',
    '  display: grid;',
    '  place-items: center;',
    '  border-radius: var(--m2kai-radius-sm);',
    '  font-size: 13px;',
    '  font-weight: 700;',
    '  color: var(--m2kai-on-accent);',
    '}',
    '.m2kai-avatar.av-openai    { background: oklch(0.62 0.13 168); }',
    '.m2kai-avatar.av-anthropic { background: oklch(0.64 0.14 47); }',
    '.m2kai-avatar.av-gemini    { background: oklch(0.60 0.15 255); }',
    '.m2kai-avatar.av-custom    { background: var(--m2kai-surface-3); color: var(--m2kai-accent-strong); border: 1px solid var(--m2kai-border-strong); }',
    '@supports not (color: oklch(0.5 0.1 264)) {',
    '  .m2kai-avatar.av-openai    { background: #19a974; }',
    '  .m2kai-avatar.av-anthropic { background: #d97757; }',
    '  .m2kai-avatar.av-gemini    { background: #4385f5; }',
    '}',
    '.m2kai-pcard-main { flex: 1; min-width: 0; }',
    '.m2kai-pcard-name {',
    '  font-size: 13px;',
    '  font-weight: 600;',
    '  white-space: nowrap;',
    '  overflow: hidden;',
    '  text-overflow: ellipsis;',
    '}',
    '.m2kai-pcard-meta {',
    '  font-size: 11px;',
    '  color: var(--m2kai-fg-faint);',
    '  white-space: nowrap;',
    '  overflow: hidden;',
    '  text-overflow: ellipsis;',
    '}',
    '',
    '.m2kai-active-dot {',
    '  width: 8px; height: 8px;',
    '  flex: none;',
    '  border-radius: 50%;',
    '  background: var(--m2kai-brand);',
    '  position: relative;',
    '  display: none;',
    '}',
    '.m2kai-pcard.is-active .m2kai-active-dot { display: block; }',
    '.m2kai-active-dot::after {',
    '  content: "";',
    '  position: absolute;',
    '  inset: 0;',
    '  border-radius: 50%;',
    '  background: var(--m2kai-brand);',
    '  animation: m2kai-pulse 2.4s ease-out infinite;',
    '}',
    '@keyframes m2kai-pulse {',
    '  0%   { transform: scale(1); opacity: 0.5; }',
    '  70%  { transform: scale(2); opacity: 0; }',
    '  100% { transform: scale(2); opacity: 0; }',
    '}',
    '',
    '.m2kai-addcard {',
    '  display: flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  gap: var(--m2kai-s1);',
    '  padding: var(--m2kai-s2) var(--m2kai-s3);',
    '  border: 1px dashed var(--m2kai-border-strong);',
    '  background: transparent;',
    '  border-radius: var(--m2kai-radius-md);',
    '  color: var(--m2kai-fg-muted);',
    '  font-size: 13px;',
    '  font-weight: 500;',
    '  cursor: pointer;',
    '  transition: border-color 0.13s, color 0.13s, background 0.13s;',
    '}',
    '.m2kai-addcard:hover { border-color: var(--m2kai-accent); color: var(--m2kai-accent-strong); background: var(--m2kai-accent-weak); }',
    '.m2kai-addcard:focus-visible { outline: none; box-shadow: 0 0 0 3px var(--m2kai-accent-ring); }',
    '',
    '/* Detail 右欄 */',
    '.m2kai-md-detail {',
    '  overflow: auto;',
    '  padding: var(--m2kai-s5) var(--m2kai-s5);',
    '}',
    '.m2kai-detail-head {',
    '  display: flex;',
    '  align-items: center;',
    '  gap: var(--m2kai-s3);',
    '  margin-bottom: var(--m2kai-s1);',
    '}',
    '.m2kai-detail-head .m2kai-avatar { width: 36px; height: 36px; font-size: 15px; }',
    '.m2kai-detail-title { font-size: 16px; font-weight: 700; }',
    '.m2kai-detail-sub { font-size: 12px; color: var(--m2kai-fg-muted); }',
    '',
    '.m2kai-onboard {',
    '  display: flex;',
    '  align-items: flex-start;',
    '  gap: var(--m2kai-s2);',
    '  margin-top: var(--m2kai-s3);',
    '  padding: var(--m2kai-s2) var(--m2kai-s3);',
    '  border-radius: var(--m2kai-radius-md);',
    '  background: var(--m2kai-accent-weak);',
    '  color: var(--m2kai-accent-strong);',
    '  font-size: 12px;',
    '  line-height: 1.5;',
    '}',
    '.m2kai-onboard .m2kai-ico { width: 14px; height: 14px; flex: none; margin-top: 2px; }',
    '',
    '.m2kai-use-row {',
    '  display: flex;',
    '  align-items: center;',
    '  gap: var(--m2kai-s2);',
    '  margin: var(--m2kai-s3) 0 var(--m2kai-s1);',
    '  padding: var(--m2kai-s2) var(--m2kai-s3);',
    '  border-radius: var(--m2kai-radius-md);',
    '  background: var(--m2kai-surface-2);',
    '  border: 1px solid var(--m2kai-border);',
    '  font-size: 12px;',
    '  color: var(--m2kai-fg-muted);',
    '}',
    '.m2kai-use-row.is-active {',
    '  background: var(--m2kai-brand-weak);',
    '  border-color: var(--m2kai-brand);',
    '  color: var(--m2kai-accent-strong);',
    '  font-weight: 600;',
    '}',
    '.m2kai-use-row .m2kai-spacer { flex: 1; }',
    '',
    '/* =========================================================================',
    '   表單元件',
    '   ========================================================================= */',
    '.m2kai-field { margin-top: var(--m2kai-s4); }',
    '.m2kai-field.is-tight { margin-top: var(--m2kai-s2); }',
    '.m2kai-label {',
    '  display: block;',
    '  font-size: 12px;',
    '  font-weight: 600;',
    '  color: var(--m2kai-fg);',
    '  margin-bottom: var(--m2kai-s2);',
    '}',
    '.m2kai-label .m2kai-req { color: var(--m2kai-danger); margin-left: 2px; }',
    '.m2kai-hint {',
    '  font-size: 12px;',
    '  color: var(--m2kai-fg-faint);',
    '  margin-top: var(--m2kai-s1);',
    '}',
    '.m2kai-hint code {',
    '  font-family: var(--m2kai-mono);',
    '  font-size: 11px;',
    '  padding: 1px 4px;',
    '  border-radius: 4px;',
    '  background: var(--m2kai-surface-3);',
    '}',
    '.m2kai-field-err {',
    '  display: none;',
    '  font-size: 12px;',
    '  color: var(--m2kai-danger);',
    '  margin-top: var(--m2kai-s1);',
    '}',
    '.m2kai-field.has-err .m2kai-field-err { display: block; }',
    '',
    '.m2kai-input,',
    '.m2kai-select,',
    '.m2kai-textarea {',
    '  width: 100%;',
    '  height: 32px;',
    '  padding: 0 10px;',
    '  background: var(--m2kai-field-bg);',
    '  border: 1px solid var(--m2kai-border-strong);',
    '  border-radius: var(--m2kai-radius-md);',
    '  color: var(--m2kai-fg);',
    '  outline: none;',
    '  appearance: none;',
    '  -webkit-appearance: none;',
    '  transition: border-color 0.13s, box-shadow 0.13s;',
    '}',
    '.m2kai-textarea {',
    '  height: auto;',
    '  min-height: 72px;',
    '  padding: var(--m2kai-s2) 10px;',
    '  resize: vertical;',
    '  line-height: 1.5;',
    '}',
    '.m2kai-input:focus,',
    '.m2kai-select:focus,',
    '.m2kai-textarea:focus {',
    '  border-color: var(--m2kai-accent);',
    '  box-shadow: 0 0 0 3px var(--m2kai-accent-ring);',
    '}',
    '.m2kai-input::placeholder,',
    '.m2kai-textarea::placeholder { color: var(--m2kai-fg-faint); }',
    '.m2kai-field.has-err .m2kai-input {',
    '  border-color: var(--m2kai-danger);',
    '  box-shadow: 0 0 0 3px var(--m2kai-danger-weak);',
    '}',
    '.m2kai-mono { font-family: var(--m2kai-mono); font-size: 13px; }',
    '',
    '.m2kai-select {',
    '  background-image:',
    '    linear-gradient(45deg, transparent 50%, var(--m2kai-fg-muted) 50%),',
    '    linear-gradient(135deg, var(--m2kai-fg-muted) 50%, transparent 50%);',
    '  background-position:',
    '    calc(100% - 16px) 13px,',
    '    calc(100% - 11px) 13px;',
    '  background-size: 5px 5px, 5px 5px;',
    '  background-repeat: no-repeat;',
    '  padding-right: 28px;',
    '  cursor: pointer;',
    '}',
    '',
    '.m2kai-row {',
    '  display: flex;',
    '  gap: var(--m2kai-s2);',
    '  align-items: center;',
    '}',
    '.m2kai-row .m2kai-input,',
    '.m2kai-row .m2kai-select { flex: 1; }',
    '',
    '/* Button */',
    '.m2kai-btn {',
    '  height: 32px;',
    '  padding: 0 var(--m2kai-s3);',
    '  display: inline-flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  gap: var(--m2kai-s1);',
    '  border-radius: var(--m2kai-radius-md);',
    '  border: 1px solid var(--m2kai-border-strong);',
    '  background: var(--m2kai-surface);',
    '  color: var(--m2kai-fg);',
    '  font-size: 13px;',
    '  font-weight: 500;',
    '  cursor: pointer;',
    '  white-space: nowrap;',
    '  transition: background 0.13s, border-color 0.13s, transform 0.06s, box-shadow 0.13s;',
    '}',
    '.m2kai-btn .m2kai-ico { width: 14px; height: 14px; }',
    '.m2kai-btn:hover { background: var(--m2kai-surface-2); border-color: var(--m2kai-fg-faint); }',
    '.m2kai-btn:active { transform: translateY(1px); }',
    '.m2kai-btn:focus-visible { outline: none; box-shadow: 0 0 0 3px var(--m2kai-accent-ring); }',
    '.m2kai-btn:disabled { opacity: 0.55; cursor: default; }',
    '.m2kai-btn:disabled:hover { background: var(--m2kai-surface); border-color: var(--m2kai-border-strong); transform: none; }',
    '.m2kai-btn-primary {',
    '  background: var(--m2kai-accent);',
    '  border-color: var(--m2kai-accent);',
    '  color: var(--m2kai-on-accent);',
    '  font-weight: 600;',
    '}',
    '.m2kai-btn-primary:hover { background: var(--m2kai-accent-strong); border-color: var(--m2kai-accent-strong); }',
    '.m2kai-btn-primary:disabled:hover { background: var(--m2kai-accent); border-color: var(--m2kai-accent); }',
    '.m2kai-btn-ghost { border-color: transparent; background: transparent; color: var(--m2kai-fg-muted); }',
    '.m2kai-btn-ghost:hover { background: var(--m2kai-surface-2); color: var(--m2kai-fg); }',
    '.m2kai-btn-danger {',
    '  border-color: transparent;',
    '  background: var(--m2kai-danger-weak);',
    '  color: var(--m2kai-danger);',
    '}',
    '.m2kai-btn-danger:hover { background: var(--m2kai-danger); color: oklch(0.99 0 0); }',
    '.m2kai-btn-sm { height: 28px; padding: 0 10px; font-size: 12px; }',
    '',
    '/* password 顯示/隱藏 + 測試連線 同列 */',
    '.m2kai-key-wrap { position: relative; flex: 1; }',
    '.m2kai-key-wrap .m2kai-input { padding-right: 40px; }',
    '.m2kai-key-toggle {',
    '  position: absolute;',
    '  right: 4px; top: 4px;',
    '  width: 24px; height: 24px;',
    '  display: grid; place-items: center;',
    '  border: none;',
    '  background: transparent;',
    '  color: var(--m2kai-fg-faint);',
    '  border-radius: 5px;',
    '  cursor: pointer;',
    '  transition: color 0.12s, background 0.12s;',
    '}',
    '.m2kai-key-toggle .m2kai-ico { width: 15px; height: 15px; }',
    '.m2kai-key-toggle:hover { color: var(--m2kai-fg); background: var(--m2kai-surface-3); }',
    '.m2kai-key-toggle:focus-visible { outline: none; box-shadow: 0 0 0 2px var(--m2kai-accent-ring); }',
    '',
    '/* Spinner */',
    '.m2kai-spinner {',
    '  width: 13px; height: 13px;',
    '  border: 2px solid currentColor;',
    '  border-right-color: transparent;',
    '  border-radius: 50%;',
    '  animation: m2kai-spin 0.6s linear infinite;',
    '  display: inline-block;',
    '}',
    '@keyframes m2kai-spin { to { transform: rotate(360deg); } }',
    '',
    '/* 測試＋抓取 合一狀態訊息 */',
    '.m2kai-status {',
    '  display: none;',
    '  align-items: center;',
    '  gap: var(--m2kai-s1);',
    '  margin-top: var(--m2kai-s2);',
    '  padding: var(--m2kai-s2) var(--m2kai-s3);',
    '  border-radius: var(--m2kai-radius-md);',
    '  font-size: 12px;',
    '  font-weight: 500;',
    '}',
    '.m2kai-status.is-shown { display: flex; animation: m2kai-fade 0.18s; }',
    '@keyframes m2kai-fade { from { opacity: 0; transform: translateY(-2px); } to { opacity: 1; transform: none; } }',
    '.m2kai-status.st-loading { background: var(--m2kai-surface-2); color: var(--m2kai-fg-muted); border: 1px solid var(--m2kai-border); }',
    '.m2kai-status.st-ok      { background: var(--m2kai-success-weak); color: var(--m2kai-success); border: 1px solid var(--m2kai-success-border); }',
    '.m2kai-status.st-err     { background: var(--m2kai-danger-weak); color: var(--m2kai-danger); border: 1px solid var(--m2kai-danger-border); }',
    '.m2kai-status .m2kai-spacer { flex: 1; }',
    '.m2kai-status .m2kai-ico { width: 14px; height: 14px; flex: none; }',
    '',
    '/* 可搜尋模型下拉 */',
    '.m2kai-modelpicker { position: relative; margin-top: var(--m2kai-s2); display: none; }',
    '.m2kai-modelpicker.is-shown { display: block; animation: m2kai-fade 0.18s; }',
    '.m2kai-search-wrap { position: relative; }',
    '.m2kai-search-icon {',
    '  position: absolute; left: 9px; top: 50%; transform: translateY(-50%);',
    '  color: var(--m2kai-fg-faint); pointer-events: none;',
    '  width: 14px; height: 14px;',
    '}',
    '.m2kai-modelpicker .m2kai-input { padding-left: 30px; }',
    '.m2kai-modellist {',
    '  margin-top: var(--m2kai-s1);',
    '  max-height: 168px;',
    '  overflow: auto;',
    '  border: 1px solid var(--m2kai-border);',
    '  border-radius: var(--m2kai-radius-md);',
    '  background: var(--m2kai-surface);',
    '}',
    '.m2kai-modelopt {',
    '  display: flex;',
    '  align-items: center;',
    '  gap: var(--m2kai-s2);',
    '  padding: var(--m2kai-s2) var(--m2kai-s3);',
    '  cursor: pointer;',
    '  font-family: var(--m2kai-mono);',
    '  font-size: 12px;',
    '  border-bottom: 1px solid var(--m2kai-border);',
    '  transition: background 0.1s;',
    '}',
    '.m2kai-modelopt:last-child { border-bottom: none; }',
    '.m2kai-modelopt:hover { background: var(--m2kai-surface-2); }',
    '.m2kai-modelopt.is-selected { background: var(--m2kai-accent-weak); color: var(--m2kai-accent-strong); font-weight: 600; }',
    '.m2kai-modelopt .m2kai-check { margin-left: auto; color: var(--m2kai-accent); opacity: 0; width: 14px; height: 14px; }',
    '.m2kai-modelopt.is-selected .m2kai-check { opacity: 1; }',
    '.m2kai-modelempty { padding: var(--m2kai-s4); text-align: center; color: var(--m2kai-fg-faint); font-size: 12px; }',
    '',
    '/* Badge */',
    '.m2kai-badge {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  gap: var(--m2kai-s1);',
    '  height: 19px;',
    '  padding: 0 7px;',
    '  border-radius: 999px;',
    '  font-size: 11px;',
    '  font-weight: 600;',
    '  background: var(--m2kai-surface-3);',
    '  color: var(--m2kai-fg-muted);',
    '}',
    '.m2kai-badge.bd-active { background: var(--m2kai-brand-weak); color: var(--m2kai-accent-strong); }',
    '.m2kai-badge.bd-local  { background: var(--m2kai-warn-weak); color: var(--m2kai-warn); }',
    '',
    '/* 角落「使用中」小 badge */',
    '.m2kai-corner-badge {',
    '  position: absolute;',
    '  top: -7px; right: 8px;',
    '  height: 16px;',
    '  padding: 0 6px;',
    '  border-radius: 999px;',
    '  font-size: 10px;',
    '  font-weight: 700;',
    '  letter-spacing: 0.02em;',
    '  background: var(--m2kai-brand);',
    '  color: var(--m2kai-on-accent);',
    '  display: none;',
    '  align-items: center;',
    '}',
    '.m2kai-pcard.is-active .m2kai-corner-badge { display: inline-flex; }',
    '',
    '/* Switch */',
    '.m2kai-switch {',
    '  position: relative;',
    '  width: 36px; height: 20px;',
    '  flex: none;',
    '  display: inline-block;',
    '  cursor: pointer;',
    '}',
    '.m2kai-switch input { position: absolute; opacity: 0; width: 0; height: 0; }',
    '.m2kai-switch-track {',
    '  position: absolute; inset: 0;',
    '  background: var(--m2kai-border-strong);',
    '  border-radius: 999px;',
    '  transition: background 0.16s;',
    '}',
    '.m2kai-switch-thumb {',
    '  position: absolute;',
    '  top: 2px; left: 2px;',
    '  width: 16px; height: 16px;',
    '  background: var(--m2kai-surface);',
    '  border: 1px solid var(--m2kai-border-strong);',
    '  border-radius: 50%;',
    '  box-shadow: 0 1px 2px oklch(0 0 0 / 0.2);',
    '  transition: transform 0.16s cubic-bezier(0.2, 0.8, 0.3, 1);',
    '}',
    '.m2kai-switch input:checked + .m2kai-switch-track { background: var(--m2kai-accent); }',
    '.m2kai-switch input:checked + .m2kai-switch-track .m2kai-switch-thumb { transform: translateX(16px); border-color: transparent; }',
    '.m2kai-switch input:focus-visible + .m2kai-switch-track { box-shadow: 0 0 0 3px var(--m2kai-accent-ring); }',
    '',
    '/* =========================================================================',
    '   Tab 2 回覆',
    '   ========================================================================= */',
    '.m2kai-section {',
    '  padding: var(--m2kai-s5) var(--m2kai-s5);',
    '  max-width: 720px;',
    '}',
    '.m2kai-section-title {',
    '  font-size: 13px;',
    '  font-weight: 700;',
    '  color: var(--m2kai-fg);',
    '  margin: 0 0 2px;',
    '}',
    '.m2kai-section-desc {',
    '  font-size: 12px;',
    '  color: var(--m2kai-fg-muted);',
    '  margin-bottom: var(--m2kai-s3);',
    '}',
    '.m2kai-divider { height: 1px; background: var(--m2kai-border); margin: var(--m2kai-s5) 0; }',
    '',
    '/* 規則卡 */',
    '.m2kai-rule {',
    '  border: 1px solid var(--m2kai-border);',
    '  border-radius: var(--m2kai-radius-md);',
    '  background: var(--m2kai-surface-2);',
    '  margin-bottom: var(--m2kai-s2);',
    '  overflow: hidden;',
    '  transition: border-color 0.13s, box-shadow 0.13s;',
    '}',
    '.m2kai-rule:hover { border-color: var(--m2kai-border-strong); }',
    '.m2kai-rule.is-disabled { opacity: 0.62; }',
    '.m2kai-rule-topbar {',
    '  display: flex;',
    '  align-items: center;',
    '  gap: var(--m2kai-s2);',
    '  padding-right: var(--m2kai-s3);',
    '}',
    '.m2kai-rule-head {',
    '  display: flex;',
    '  align-items: center;',
    '  gap: var(--m2kai-s2);',
    '  flex: 1;',
    '  min-width: 0;',
    '  padding: var(--m2kai-s2) var(--m2kai-s3);',
    '  background: transparent;',
    '  border: none;',
    '  text-align: left;',
    '  cursor: pointer;',
    '  color: inherit;',
    '  border-radius: var(--m2kai-radius-md) var(--m2kai-radius-md) 0 0;',
    '}',
    '.m2kai-rule-head:focus-visible { outline: none; box-shadow: inset 0 0 0 2px var(--m2kai-accent-ring); }',
    '.m2kai-rule-controls { display: flex; align-items: center; gap: var(--m2kai-s2); flex: none; }',
    '.m2kai-chevron {',
    '  color: var(--m2kai-fg-faint);',
    '  transition: transform 0.16s;',
    '  width: 12px; height: 12px;',
    '  flex: none;',
    '}',
    '.m2kai-rule.is-open .m2kai-chevron { transform: rotate(90deg); }',
    '.m2kai-rule-name { font-size: 13px; font-weight: 600; flex: 1; min-width: 0; }',
    '.m2kai-rule-name .m2kai-rule-match {',
    '  font-weight: 400;',
    '  color: var(--m2kai-fg-faint);',
    '  font-size: 12px;',
    '  margin-left: var(--m2kai-s1);',
    '  font-family: var(--m2kai-mono);',
    '}',
    '.m2kai-rule-body {',
    '  display: none;',
    '  padding: 0 var(--m2kai-s3) var(--m2kai-s3) var(--m2kai-s6);',
    '  border-top: 1px solid var(--m2kai-border);',
    '  padding-top: var(--m2kai-s3);',
    '}',
    '.m2kai-rule.is-open .m2kai-rule-body { display: block; animation: m2kai-fade 0.18s; }',
    '.m2kai-rule-grid {',
    '  display: grid;',
    '  grid-template-columns: 140px 1fr;',
    '  gap: var(--m2kai-s2);',
    '  margin-bottom: var(--m2kai-s2);',
    '}',
    '.m2kai-iconbtn-sm {',
    '  width: 26px; height: 26px;',
    '  flex: none;',
    '  display: grid; place-items: center;',
    '  border: 1px solid var(--m2kai-border);',
    '  background: var(--m2kai-surface);',
    '  border-radius: var(--m2kai-radius-sm);',
    '  color: var(--m2kai-fg-faint);',
    '  cursor: pointer;',
    '  transition: color 0.12s, border-color 0.12s, background 0.12s;',
    '}',
    '.m2kai-iconbtn-sm .m2kai-ico { width: 14px; height: 14px; }',
    '.m2kai-iconbtn-sm:hover { color: var(--m2kai-danger); border-color: var(--m2kai-danger); background: var(--m2kai-danger-weak); }',
    '.m2kai-iconbtn-sm:focus-visible { outline: none; box-shadow: 0 0 0 2px var(--m2kai-accent-ring); }',
    '.m2kai-iconbtn-sm.is-confirm {',
    '  width: auto;',
    '  padding: 0 var(--m2kai-s2);',
    '  font-size: 11px;',
    '  font-weight: 600;',
    '  color: var(--m2kai-on-accent);',
    '  background: var(--m2kai-danger);',
    '  border-color: var(--m2kai-danger);',
    '}',
    '.m2kai-num { max-width: 140px; }',
    '',
    '/* 空狀態卡 */',
    '.m2kai-empty {',
    '  display: flex;',
    '  flex-direction: column;',
    '  align-items: center;',
    '  gap: var(--m2kai-s3);',
    '  padding: var(--m2kai-s6) var(--m2kai-s4);',
    '  border: 1px dashed var(--m2kai-border-strong);',
    '  border-radius: var(--m2kai-radius-md);',
    '  background: var(--m2kai-surface-2);',
    '  color: var(--m2kai-fg-muted);',
    '  text-align: center;',
    '}',
    '.m2kai-empty .m2kai-empty-ico { width: 28px; height: 28px; color: var(--m2kai-fg-faint); }',
    '.m2kai-empty-title { font-size: 13px; font-weight: 600; color: var(--m2kai-fg); }',
    '.m2kai-empty-desc { font-size: 12px; line-height: 1.5; max-width: 360px; }',
    '',
    '/* =========================================================================',
    '   Tab 3 進階',
    '   ========================================================================= */',
    '.m2kai-toggle-row {',
    '  display: flex;',
    '  align-items: flex-start;',
    '  gap: var(--m2kai-s3);',
    '  padding: var(--m2kai-s3);',
    '  border: 1px solid var(--m2kai-border);',
    '  border-radius: var(--m2kai-radius-md);',
    '  background: var(--m2kai-surface-2);',
    '  margin-bottom: var(--m2kai-s3);',
    '}',
    '.m2kai-toggle-row .m2kai-tr-main { flex: 1; }',
    '.m2kai-tr-title { font-size: 13px; font-weight: 600; }',
    '.m2kai-tr-desc { font-size: 12px; color: var(--m2kai-fg-muted); margin-top: 2px; }',
    '',
    '.m2kai-about {',
    '  padding: var(--m2kai-s4);',
    '  border: 1px solid var(--m2kai-border);',
    '  border-radius: var(--m2kai-radius-md);',
    '  background: var(--m2kai-surface-2);',
    '}',
    '.m2kai-about-row { display: flex; align-items: center; gap: var(--m2kai-s3); }',
    '.m2kai-about-meta { font-size: 12px; color: var(--m2kai-fg-muted); }',
    '.m2kai-safety {',
    '  display: flex;',
    '  align-items: center;',
    '  gap: var(--m2kai-s2);',
    '  margin-top: var(--m2kai-s3);',
    '  padding: var(--m2kai-s3);',
    '  border-radius: var(--m2kai-radius-md);',
    '  background: var(--m2kai-success-weak);',
    '  border: 1px solid var(--m2kai-success-border);',
    '  color: var(--m2kai-success);',
    '  font-size: 13px;',
    '  font-weight: 600;',
    '}',
    '.m2kai-safety .m2kai-ico { width: 16px; height: 16px; flex: none; }',
    '',
    '/* =========================================================================',
    '   Footer',
    '   ========================================================================= */',
    '.m2kai-footer {',
    '  display: flex;',
    '  align-items: center;',
    '  gap: var(--m2kai-s3);',
    '  padding: var(--m2kai-s3) var(--m2kai-s4);',
    '  border-top: 1px solid var(--m2kai-border);',
    '  background: var(--m2kai-surface);',
    '}',
    '.m2kai-footer-note {',
    '  flex: 1;',
    '  display: flex;',
    '  align-items: center;',
    '  gap: var(--m2kai-s2);',
    '  font-size: 12px;',
    '  color: var(--m2kai-fg-faint);',
    '}',
    '.m2kai-dirty-dot {',
    '  width: 7px; height: 7px;',
    '  border-radius: 50%;',
    '  background: var(--m2kai-warn);',
    '  flex: none;',
    '  display: none;',
    '}',
    '.m2kai-footer.is-dirty .m2kai-dirty-dot { display: inline-block; }',
    '.m2kai-footer.is-dirty .m2kai-footer-note-clean { display: none; }',
    '.m2kai-footer-note-dirty { display: none; color: var(--m2kai-warn); font-weight: 600; }',
    '.m2kai-footer.is-dirty .m2kai-footer-note-dirty { display: inline; }',
    '',
    '/* 儲存成功微回饋 */',
    '.m2kai-saved-flash {',
    '  animation: m2kai-saved 0.5s ease;',
    '}',
    '@keyframes m2kai-saved {',
    '  0% { box-shadow: 0 0 0 0 var(--m2kai-accent-ring); }',
    '  60% { box-shadow: 0 0 0 6px transparent; }',
    '  100% { box-shadow: 0 0 0 0 transparent; }',
    '}',
    '',
    '/* Toast */',
    '.m2kai-toast {',
    '  position: fixed;',
    '  bottom: var(--m2kai-s5);',
    '  left: 50%;',
    '  transform: translateX(-50%) translateY(12px);',
    '  background: var(--m2kai-fg);',
    '  color: var(--m2kai-bg);',
    '  padding: var(--m2kai-s2) var(--m2kai-s4);',
    '  border-radius: 999px;',
    '  font-size: 13px;',
    '  font-weight: 500;',
    '  box-shadow: var(--m2kai-shadow-pop);',
    '  opacity: 0;',
    '  pointer-events: none;',
    '  transition: opacity 0.2s, transform 0.2s;',
    '  z-index: 10;',
    '}',
    '.m2kai-toast.is-shown { opacity: 1; transform: translateX(-50%) translateY(0); }',
    '',
    '/* scrollbar（Chromium 系；其他瀏覽器退化為原生） */',
    '.m2kai-root *::-webkit-scrollbar { width: 10px; height: 10px; }',
    '.m2kai-root *::-webkit-scrollbar-thumb {',
    '  background: var(--m2kai-border-strong);',
    '  border-radius: 999px;',
    '  border: 3px solid transparent;',
    '  background-clip: padding-box;',
    '}',
    '.m2kai-root *::-webkit-scrollbar-thumb:hover { background: var(--m2kai-fg-faint); background-clip: padding-box; border: 3px solid transparent; }',
    '',
    '/* inline SVG icon 預設尺寸（用 currentColor，隨 fg/accent/brand 變色） */',
    '.m2kai-ico { display: inline-block; vertical-align: middle; fill: none; stroke: currentColor; stroke-width: 2; stroke-linecap: round; stroke-linejoin: round; }',
    '',
    '/* 尊重 reduced-motion（掛在 .m2kai-root 下，不污染宿主） */',
    '@media (prefers-reduced-motion: reduce) {',
    '  .m2kai-root *,',
    '  .m2kai-panel,',
    '  .m2kai-toast {',
    '    animation-duration: 0.001s !important;',
    '    animation-iteration-count: 1 !important;',
    '    transition-duration: 0.001s !important;',
    '  }',
    '}'
  ].join('\n');

  var style = d.createElement('style');
  style.id = 'm2kaiStyle';
  style.textContent = css;
  (d.head || d.documentElement).appendChild(style);
}
